version: "3.3"

#Konfigurácia inšpirovaná https://github.com/Evolveum/midpoint-docker
#V prípade potreby lepšieho zabezpečenia je potrebné zmeniť heslo na bezpečnejšie
#Pre potreby otvorenia portu databázy je potrebné doplniť presmerovanie portu 5432 postrgresql databázy

services:
  midpoint_data:
    image: postgres:16-alpine
    environment:
     - POSTGRES_PASSWORD=dbheslo_tajne
     - POSTGRES_USER=midpoint_main
     - POSTGRES_INITDB_ARGS=--lc-collate=en_US.utf8 --lc-ctype=en_US.utf8
    networks:
     - net
    volumes:  #defines local folder
     - ./data/midpoint_data:/var/lib/postgresql/data
      

  data_init:
    image: evolveum/midpoint:${MP_VER:-latest}-alpine
    command: >
        bash -c "
        cd /opt/midpoint ;
        bin/midpoint.sh init-native ;
        echo ' - - - - - - ' ;
        if [ $$(bin/ninja.sh verify 2>&1 | grep -c 'ERROR' ) -gt 0 ] ;
        then
        bin/ninja.sh run-sql --create --mode REPOSITORY ;
        bin/ninja.sh run-sql --create --mode AUDIT ;
        else
        echo -e '\\n Repository init is not needed...' ;
        fi ;
        "
    depends_on:
     - midpoint_data
    environment:
     - MP_SET_midpoint_repository_jdbcUsername=midpoint_main
     - MP_SET_midpoint_repository_jdbcPassword=dbheslo_tajne
     - MP_SET_midpoint_repository_jdbcUrl=jdbc:postgresql://midpoint_data:5432/midpoint
     - MP_SET_midpoint_repository_database=postgresql
     - MP_INIT_CFG=/opt/midpoint/var
    networks:
     - net
    volumes: #defines local folder
     - ./data/midpoint_home:/opt/midpoint/var

#Používa interný midpoint.sh skript navrhnutý na zjednodušenie behu a konfigurácie podľa env variables
  midpoint_server:
    image: evolveum/midpoint:${MP_VER:-latest}-alpine
    container_name: midpoint_server_idm
    hostname: midpoint-container-idm
    depends_on:
      data_init:
        condition: service_completed_successfully
      midpoint_data:
        condition: service_started
    command: [ "/opt/midpoint/bin/midpoint.sh", "container" ]
    ports:
      - 8080:8080
      - 5005:5005 #debug port
    environment:
     - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 #debug being used for developement
     - MP_SET_midpoint_repository_jdbcUsername=midpoint_main
     - MP_SET_midpoint_repository_jdbcPassword=dbheslo_tajne
     - MP_SET_midpoint_repository_jdbcUrl=jdbc:postgresql://midpoint_data:5432/midpoint
     - MP_SET_midpoint_repository_database=postgresql
     - MP_UNSET_midpoint_repository_hibernateHbm2ddl=1
     - MP_NO_ENV_COMPAT=1
    networks:
     - net
    volumes: #define local folder
     - ./data/midpoint_home:/opt/midpoint/var

#jednoduchý network bridge
networks:
  net:
    driver: bridge

